### ISSUE TITLE
DB schemas: States, Districts, Members of Congress

### ISSUE THREAD

**Issue by gnmerritt** [gnmerritt/dailyrippl#1]

**Comment by samgqroberts** [comment]
hey do you wanna brain-dump plans of (maybe scoped to V1) functionality somewhere here? maybe even just a comment on this issue, so we can start thinking more holistically about stuff like schema design, so forth

**Comment by gnmerritt** [comment]
For starters I'm building an import script for the yaml in https://github.com/unitedstates/congress-legislators which gobbles up representatives, their served terms in congress and their contact info
